# EVM
# Clients
evm_client.connect_timeout_seconds = 10
evm_client.read_timeout_seconds = 10
evm_client.write_timeout_seconds = 10

# Network properties on format evm.<network-id>.<property>

# List of evm rpc urls separated by comma
evm.1.rpc_urls = http://localhost:33253

# Private key can either be retrieved from node configuration file or set directly as property in this config
evm.1.node_config_file = ../directory1-example/config/config.0.properties
#evm.1.node_private_key = dsf

# Never read beyond head-readOffset blocks
evm.1.log.readOffset=200

# Block range to request as maximum per log request
evm.1.log.maxBlockRangePerRequest=500

# Idling delay between log poll
evm.1.log.delayWhenNoNewBlock=2000

# Postchain
postchain.url = http://localhost:7740
# Blockchain RID - Either economy chain for dapp bridges or transaction submitter chain for system bridges
postchain.blockchain_rid = 0000000000000000000000000000000000000000000000000000000000000002
# Interval in milliseconds to query the blockchain for bridges to monitor
postchain.bridge_chain_refresh_interval = 1200000

# Bridge anomaly detector
# Specified in minutes - 24h
missing_height_retry_delay=1440
# Specified in minutes - 2h
pause_delay=120

# Port used by REST API server, -1 to disable
rest_api.port = 7790
